theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

site_name: World Foundation Models

nav:
  - Home: index.md

  - Projeto:
      - Visão Geral: projeto/visaoGeral/visaoGeral.md
      - Motivação: projeto/motivacao/motivacao.md
      - Contextualização: projeto/contextualizacao/contextualizacao.md
      - Metodologia: projeto/metodologia/metodologia.md
      - Proposta: projeto/proposta/proposta.md
      - Escopo: projeto/escopo.md

  - Referências:
      - Diffusion Models: diffusion/diffusion.md
      - Autoregressive Models: autoregressive/autoregressive.md
      - Tokens:
          - Visão Geral: projeto/escopo.md
          - Cosmos Tokenizer:
              - Introdução: tokens/cosmos_tokenizer/cosmos_tokenizer.md
              - Wavelet Compression: tokens/cosmos_tokenizer/wavelet_compression.ipynb
          - DSC Tokenization: tokens/dsc_tokenization.md

  - Experiments & Results: cosmos_applications/cosmos_applications.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocs-jupyter:
      execute: true
      include_source: true
      include:
        - "*.ipynb"